### ISSUE TITLE
Link wrong

### ISSUE THREAD

**Issue by Icelk** [Foundry376/Mailspring-Theme-Starter#13]
Link to file in Mailspring repo is wrong in file `styles/ui-variables.less`
<https://github.com/Foundry376/Mailspring/blob/master/app/static/base/ui-variables.less#L37:L40>
should be changed to
<https://github.com/Foundry376/Mailspring/blob/master/app/static/style/base/ui-variables.less>

**Comment by Icelk** [comment]
Should I make a PR fixing the issue?

**Comment by bengotow** [comment]
Hey Icelk! Thanks for reaching out - if you could submit a small PR for
this that'd be great! It's definitely a fix we need to make.

**Comment by Icelk** [comment]
Sure!
