### ISSUE TITLE
Main reading panel color

### ISSUE THREAD

**Issue by reya276** [Foundry376/Mailspring-Theme-Starter#3]
I have created my own theme. However some emails are not displaying correctly due to the background color being #2D2C2E so sometimes the text color does not show. Is there any way to change this particular panel to white (#fff).
![mailspring](https://user-images.githubusercontent.com/25517972/50008652-dc339700-ff82-11e8-8765-9e93547fceaf.png)

**Comment by CaptainJawZ** [comment]
Did you ever found out how? I too strugle with this.

**Comment by bengotow** [comment]
Hey folks—you should be able to do this by adding a CSS Rule to your theme's index.css file like this:

```
#message-list .message-item-white-wrap {
   background: #fff;
}
```
