### ISSUE TITLE
Make Repository a Template Repository

### ISSUE THREAD

**Issue by chaitunya** [Foundry376/Mailspring-Theme-Starter#8]
I feel that this repository would work well as a [template repository](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template), since this serves as a template for Mailspring themes.

From the link:
> Creating a repository from a template is similar to forking a repository, but there are important differences:
> 
> * A new fork includes the entire commit history of the parent repository, while a repository created from a template starts with a single commit.
> * Commits to a fork don't appear in your contributions graph, while commits to a repository created from a template do appear in your contribution graph.
> * A fork can be a temporary way to contribute code to an existing project, while creating a repository from a template starts a new project quickly.

**Comment by Icelk** [comment]
Seems like a great addition!

**Comment by bengotow** [comment]
Oh hey this seems like a great idea! I didn't even know these existed actually :-) I checked the box and it seems like that's all there is to it, will do it on the plugin starter as well!
